### ISSUE TITLE
Support for replacing @JsonValue

### ISSUE THREAD

**Issue by nealeu** [bertilmuth/moonwlker#8]
Hi,

In your examples in the test, I can't see any support for flattening value types as we can do with annotations using `@JsonValue` and `@JsonCreator`.

Is this something that would be easy to add?

We might try a pull request if you're up for it.

For example, perhaps configuration would be:

```
mapper.registerModule(
    MoonwlkerModule.builder()
      .addValueType(ValueClass.class, ValueClass::externalForm)
      .build()
```

for 
```
class ValueClass {
    private final String value;
    
    public ValueClass(String value) {
        this.value = value;
    }

    // this would have had @JsonValue
    public String externalForm() {
        return value;
    }
}
```

**Comment by bertilmuth** [comment]
Can you please provide a code example of the behavior you‘d like to see implemented?

**Comment by nealeu** [comment]
Ha. I was just editing above when you commented.  Does that make sense?

**Comment by nealeu** [comment]
So the config would be 
```
mapper.registerModule(
    MoonwlkerModule.builder()
      .addValueType(ValueClass.class, ValueClass::externalForm)
      .build()
```
and it would use discover the default constructor as a single string-argument constructor as Jackson does in the absence of `@JsonCreator`

**Comment by bertilmuth** [comment]
I see, thank you. That was helpful. Maybe this could be solved with a custom (de)serializer. Maybe it would be necessary to specify the scalar type as well, e.g. by using several methods in the builder. Is there a specific project context in which you could use this feature? Or in other words: apart from „cleanliness“, is there additional value of that feature for you?

**Comment by nealeu** [comment]
Hi Bertil,

Yes, I can see I should be able to use a custom deserializer, so it's not that much different to things like date & time representations done by jackson-datatype-jsr310.

However if going down the route I proposed above I can see some value in being able to specify an interface (also we're using Kotlin, so I should look at the internals of that module regarding reification), where we'd use `ValueClass::externalForm` for serialization and the single-arg constructor for construction.

In fact the simplest approach should surely be that we can box and unbox a scalar type without the optional conversion provided by the constructor and `toExternalForm()` which fits more with custom serialization.

I think we have some time to experiment today so we'll have a further look.

**Comment by nealeu** [comment]
So far it seems that we can follow your pattern of providing an AnnotationIntrospector to specify where we want to pretend `@JsonValue` was found

**Comment by nealeu** [comment]
Hi,
It took us a while finding the various internals, but we got as far as a test case and some hacked code where it passes.

See https://github.com/springernature/moonwlker/blob/5aefa985b844255d23a9433d05357c7baaaa677d/src/test/java/org/requirementsascode/moonwlker/ValueTest.java#L71 for where we just hard-code one method where `@JsonValue` would otherwise have been needed.

**Comment by bertilmuth** [comment]
Nice! As an alternative, I created a (de)serializer based version: https://github.com/bertilmuth/moonwlker/blob/moonwlker-8/src/test/java/org/requirementsascode/moonwlker/ValueTest.java

The benefit of the (de)serializer based version is that you can use it for any kind of (de)serialization, not just a 1:1 mapping between the wrapped type and a String (which I guess is not possible with the Introspector based solution, because Jackson wouldn't know how to transform the string value to the value type). 

The downside of the (de)serializer based version would be that you'd need to register it for any ValueType class - which would be fine if these classes don't share a common interface by nature, I think. 

So my question is: how often does it happen in practice in your context that the value types share a common interface *by nature*? What I mean is this: do you need to introduce the interface just for serialization purposes?
If yes, than my question would be: why not just put the `JsonValue `annotation into that interface and be done with it ;-) ?

I'm not completely against the interface approach. I think the reference to a Method instance/method name instead of a method reference is a bit clumsy. 

Thanks for your proposal. I'm looking forward to you comments.

**Comment by nealeu** [comment]
Thanks, I wanted to use method refs too, and that didn't work for the approach we took because getting a Method from a method reference isn't supported in Java.  
Your approach solves that.

The other thing that your approach may solve is that what works in Java doesn't work for a Kotlin data class due to some issues in the Jackson Kotlin module.

Regarding your questions, then yes, the common interface does help us avoid lots of boilerplating and we do use it whenever we have an identifier, so there are 50+ of these.  However, that's 1 line of configuration vs 50x50 lines of boilerplate (just for the value types) plus tests where we currently have manual ser/deser of our domain objects.  

Actually for the "why not just put @JsonValue in", the alternative would be to use a mix-in, which would keep the purists happy.

**Comment by bertilmuth** [comment]
Well, using my approach, you’d need one line of config for each of the 50 classes, since construction is done via a class specific function.

The benefit of this is that you can even deal with other types of construction like static method constructors.

So, do you want to continue investigating your approach? Do you want me to integrate my approach into the builder? Should not be a big deal.

**Comment by bertilmuth** [comment]
Thinking about it, the mixin approach may be better suited to your needs…

**Comment by nealeu** [comment]
We've got our full test suite passing (on the first set of domain classes) passing with your solution, so we'll have a look at pushing further based on your branch if that works for you.
The mixin would be perhaps another nice option later, but for us it'd require the above Kotlin related issue resolved which I think would be a lot of time spent digging into jackson-kotlin-module for no great additional benefit.

**Comment by bertilmuth** [comment]
Sounds good to me (even though I have made minor changes to master in order to be compatible with Java 8 again - I left the gradlew updates that you committed though).

One more idea that I had (but it's unclear when I can address it): create the target instance via reflection, and use a BeanDeserializerModifier to change the deserializer on the fly. I'm not sure that works, but if it does, it could solve the interface case (having only one config line for all classes).

**Comment by nealeu** [comment]
That sounds painful and potentially fragile for supporting Jackson 3 when released though.

We've done a clean up for your branch that may make it worth squashing for master now.  I'll PR it to your branch rather than master.

**Comment by nealeu** [comment]
Many thanks Bertil.  That looks great.
We'll update to 0.3.
